### ISSUE TITLE
More custom Dockerfile

### ISSUE THREAD

**Issue by ajm188** [hacsoc/the_jolly_advisor#152]
Don't derive from rails:onbuild, as it contains a bunch of stuff we don't want or need.

**Comment by ZJaffee** [comment]
While I'm not particularly familiar with the way in which the jolly advisor uses rails, pulling the base image from the official tool on docker hub is generally the way in which one would want to take care of this unless your saying you'd want there to be a completely custom made docker image that only includes the parts of rails necessary to build the advisor.

Another idea to set up the docker build in a much better way than it is right now would be to use docker-compose which is essentially a yaml file that would build the various images, run them as containers and connect them however you specified in the docker-compose.yml file.

**Comment by ajm188** [comment]
I want the former. The official image installs nodejs, along with clients for mysql, postgres and sqlite. This is silly, even for an official image, since you will only use one client for your application.

I will take a look at docker-compose, though. Thanks for the suggestions!

**Comment by ZJaffee** [comment]
You need nodejs or some other javascript runtime environment installed for rails to work in a container, but your best option given how things are done currently would probably involve just modifying the source for from rains:onbuild and modifying it so that it only installs what you want, push that to dockerhub and then reference it as needed. 

Long term it would absolutely be worth it to use docker compose as you can configure it so that compose spins up the database as well.

**Comment by matthewbentley** [comment]
docker-compose, AFAIK, is not entirely relevant to the original issue.  I am not entirely sure why the default rails dockerfile contains all this extra stuff, but it should be possible to write a custom one that only includes rails plus the basic requirements we have (I can work on that later if needed).

Regarding compose: it ads a (rather nice) layer of abstraction that, once you have containers for all your services, allows you to define how they should be launched with respect to each other (eg, container one depends on container two and three, with certain network connections, etc).  
Two reasons it's not currently used in production: 1) it was super beta when I designed the current deploy system on docker.case.edu, and 2) its networking options are not quite flexible enough for what is needed in relation to Case's network.  1) has changed since then, but I don't think 2) has.  

I won't go into full detail of how the deploy system works now, but the TL;DR is that it is a simple replacement for docker-compose written in bash with Case's specific network needs taken into account.

**Comment by ajm188** [comment]
@ZJaffee can you explain (maybe offline?) why you need nodejs to run rails in a container? I have searched for it, and have not found an reason beyond "you just need it".

@matthewbentley I think we should look into using docker compose in prod, do you want to open another issue for it?

**Comment by ZJaffee** [comment]
I don't know all of the details, but it's my understanding that because unless you want to remove all instances of this, https://github.com/hacsoc/the_jolly_advisor/search?utf8=%E2%9C%93&q=execjs, you need to have some type of javascript runtime environment installed for it to work. Given that you are using a linux server and container, nodejs is most likely your best choice of runtime environment. https://github.com/rails/execjs has a few other runtime environments you could choose from, but installing and configuring those is most likely going to be more complicated than apt-get upgrade \ apt-get install nodejs

**Comment by ajm188** [comment]
But we already install therubyracer (https://github.com/hacsoc/the_jolly_advisor/search?utf8=%E2%9C%93&q=therubyracer&type=Code), so shouldn't that not matter?

**Comment by ZJaffee** [comment]
It shouldn't matter then, in fact what you need is really simple, I'll just make a pull request because it will be easier to show you that way

**Comment by ajm188** [comment]
Sounds good. I'll assign this to you then. Feel free to unassign if you don't feel like doing it anymore.

**Comment by ajm188** [comment]
@matthewbentley this can probably be closed now, yes?

**Comment by matthewbentley** [comment]
Probably fine.  We actually base off of ruby:2.3.0-onbuild now, so I'm not sure if the original issue is even a problem
