### ISSUE TITLE
Flaky feature tests

### ISSUE THREAD

**Issue by ajm188** [hacsoc/the_jolly_advisor#180]
Here are the ones I've identified so far:
- [x] "I can navigate to Course Show Page"
- [x] "Search by Professor"
- [x] "Search by keyword in a course description"

edit: found another one locally

**Comment by JKobyP** [comment]
![screenshot_2015-11-25_00-29-04](https://cloud.githubusercontent.com/assets/6590268/11373085/8a718c4c-930b-11e5-9891-e80a8a1e9ca7.png)

Taken from: https://travis-ci.org/hacsoc/the_jolly_advisor/builds/92203942

**Comment by JKobyP** [comment]
The numbers being compared look to be 1. The `Professor` ID of the professor used to search (`Professor.first`) and 2. The `Professor` ID associated with each `Course` in the result of the search

This is weird because you'd normally expect `Professor.first` to return an ID of 1. But still the test should work with an ID of 2 or anything else... hmm.

**Comment by ajm188** [comment]
`Professor.first` is 1 iff no professor records have been deleted

**Comment by ajm188** [comment]
@JKobyP pinging for update. are you working on this? If not, I'd like to take it. I'm in a test-writing mood :)

**Comment by ajm188** [comment]
I'm stealing this because we have builds failing

**Comment by ajm188** [comment]
For the professor one, the test is flawed. There could be a professor who's name is a prefix of another professor, so the second professor's courses would appear in the results.

**Comment by ajm188** [comment]
The "show page" test is flawed as well. If a course does not have a title, then on the explorer page it will show "Title Not Found", but on the show page it will show an empty string.
