### ISSUE TITLE
Search term conflicts

### ISSUE THREAD

**Issue by ReDaCtD** [hacsoc/the_jolly_advisor#56]
Noticed a few edge case problems with the search functionality. Specifically when searching for a subject matter like "ECON" you return several PHED courses because of the "sECONd half" text in the course title/information.

**Comment by StephHippo** [comment]
So I was thinking about this a little more, and we'll have to be careful with how we tackle this.

I think we need to make sure we're only adjusting this for course numbers/titles. Right now searching "Tekin" correctly returns results because Tekin is a subset of Gultekin. I'll try to get tests in to make sure we don't inadvertently break handling professor nicknames.

**Comment by JKobyP** [comment]
Is this closed by pull request #134?

**Comment by ajm188** [comment]
Yeah we'll close this for now...if it ends up still being an issue we can always re-open.
